name: Publish Wiki Pages
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          DEFAULT_WORKSPACE: ./wiki
          VALIDATE_MARKDOWN: true
          GITHUB_TOKEN: ${{ secrets.PAT }}
  publish-to-wiki:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Publish to GitHub Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
        with:
          path: wiki
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
  publish-to-freshdesk:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Publish KBs to Freshdesk
        env:
            API_KEY: ${{ secrets.FRESHDESK_API_KEY }}
            URL_ROOT: ${{ secrets.FRESHDESK_URL }}
        run: |
          pip install markdown
          pip install requests
          python ./publish_external_kbs.py