# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to GitHub Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
        with:
          path: wiki
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          DEFAULT_WORKSPACE: ./wiki
          VALIDATE_MARKDOWN: true
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Publish KBs to Freshdesk
        env:
            API_KEY: ${{ secrets.FRESKDESK_API_KEY }}
            URL_ROOT: ${{ secrets.FRESHDESK_URL }}
        run: |
          pip install markdown
          pip install requests
          python publish_external_kbs.py